# Generated by Django 4.2.3 on 2024-01-05 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newinvoice',
            name='customer_id',
            field=models.ForeignKey(default=170, on_delete=django.db.models.deletion.CASCADE, to='invoice_app.customer'),
            preserve_default=False,
        ),
    ]
