# Generated by Django 4.2.3 on 2024-01-08 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0003_newinvoice_purchase_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
