# Generated by Django 4.2.3 on 2024-01-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0004_adminprofile_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='file',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
