# Generated by Django 4.2.3 on 2024-01-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0005_adminprofile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='pan_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
